version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: mro-postgres
    environment:
      POSTGRES_USER: mro_user
      POSTGRES_PASSWORD: mro_password
      POSTGRES_DB: mro_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mro_user -d mro_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: mro-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: mro_user
      RABBITMQ_DEFAULT_PASS: mro_password
    ports:
      - "5672:5672" # AMQP 프로토콜
      - "15672:15672" # 관리 UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  rabbitmq_data:
