packages:
  - mro-api-gateway
  - mro-user
  - mro-product
  - libs/mro-core

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - esbuild
  - prisma
